# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

  stages:
    - stage: build
      jobs:
        - job: initilize
          steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'
        - job: second
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In first stage, job two")'
        - job: third
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In first stage, job three")'
    - stage: test
      jobs:
        - job: first
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In second stage, job one")'
        - job: second
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In second stage, job two")'
        - job: third
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In second stage, job three")'
    - stage: finish
      jobs:
        - job: first
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In third stage, job one")'
        - job: second
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In third stage, job two")'
        - job: third
          steps:
          - task: NodeTool@0
            inputs:
              scriptSource: 'inline'
              script: 'print("In third stage, job three")'







