# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: initialize 
    jobs:
      - job: first
        steps:
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSpec: '10.x'
        - script: |
              npm install
              npm run build
      - job: second
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In first stage, job two")'
      - job: third
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In first stage, job three")'
  - stage: test
    jobs:
      - job: first
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In second stage, job one")'
      - job: second
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In second stage, job two")'
      - job: third
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In second stage, job three")'
  - stage: deploy
    jobs:
      - job: first
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In third stage, job one")'
      - job: second
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In third stage, job two")'
      - job: third
        steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In third stage, job three")'







